name: Dark Regenaissance Monitor Mentions

on:
  schedule:
    # Every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  monitor-mentions:
    runs-on: ubuntu-latest

    steps:
    - name: Monitor mentions and respond
      run: |
        echo "🔍 Monitoring mentions..."
        response=$(curl -s -X POST "https://darkregenaissanceai.vercel.app/api/cron/monitor" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json" \
          -d '{"action": "check_mentions"}')
        echo "Response: $response"

    - name: Log completion
      run: |
        echo "✅ Mention monitoring completed at $(date)"
        echo "🕸️ The network watches and responds..."